name: "CI"
on: [push]
jobs:
  test:
    name: Test on go ${{ matrix.go_version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [1.12]
        os: [ubuntu-latest]
    steps:
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
        id: go
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint
        run: |
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.17.1
          ./bin/golangci-lint run
      - name: Test
        run: go test -v -cover ./...
